### ISSUE TITLE
Main page questions

### ISSUE THREAD

**Issue by almereyda** [danzajdband/hackdash#124]
I have some more questions regarding the overview on my (migrated) http://urbantext.org, as I can access my collections when searching for them, but nothing shows up on the main page : No users, no collections, no dashboards.

* My stats are not updated - everywhere it shows 0.
* I only see Collections, Dashboards, Projects or People if I search for ` `.

**Comment by pjnovas** [comment]
@almereyda good check, I forgot to show the migration:

Check this script (it will use your config.json for migration):
https://github.com/danzajdband/hackdash/blob/master/utils/dashboardsCovers.js

That script is full filling dashboards with data that you have from a previous site.

I'm gonna add that to a migration doc later.

**Comment by almereyda** [comment]
@pjnovas You're really quick in closing issues :-/

This is what happened:

```
 ~$ dokku enter hackdash
u1000@11910930ebb9:~$ ls
Gruntfile.js  client              keys.json.sample  node_modules  seo.js     views
LICENSE       config.json         live.js           package.json  server.js
Procfile      config.json.sample  mailer.js         prerender     sitemap
README.md     embed               metrics           public        test
auth.js       keys.json           models            routes        utils
u1000@11910930ebb9:~$ cd utils/
u1000@11910930ebb9:~/utils$ node dashboardsCovers.js
Updating dashboards ... 
Updated 3 dashboards
u1000@11910930ebb9:~/utils$ exit
exit
Connection to apps.ecobytes.net closed.
 ~$ dokku restart hackdash
11910930ebb9f557e4194f082863e0276f2b30413d61f24c47d8797fcb0fca79
Connection to apps.ecobytes.net closed.
 ~$ dokku status hackdash
hackdash is stopped.
Connection to apps.ecobytes.net closed.
 ~$ dokku start hackdash
11910930ebb9f557e4194f082863e0276f2b30413d61f24c47d8797fcb0fca79
Connection to apps.ecobytes.net closed.
 ~$ dokku status hackdash
hackdash is stopped.
Connection to apps.ecobytes.net closed.
 ~$ dokku logs hackdash
14:55:35 web.1  | GET /api/v2/profiles/550f8921ad56d70a0039bf06 200 16ms
14:55:38 web.1  | { [TypeError: /app/views/layout.jade:7
14:55:38 web.1  |     5|     meta(name="viewport", content="width=device-width, initial-scale=
1.0")
14:55:38 web.1  |     6| 
14:55:38 web.1  |   > 7|     title= meta.title
14:55:38 web.1  |     8|     meta(name="description", content= meta.description)
14:55:38 web.1  |     9|     link(rel='image_src', type='image/png', href= meta.image)
14:55:38 web.1  |     10| 
14:55:38 web.1  | 
14:55:38 web.1  | Cannot read property 'title' of undefined] path: '/app/views/layout.jade' }
14:55:38 web.1  | TypeError: /app/views/layout.jade:7
14:55:38 web.1  |     5|     meta(name="viewport", content="width=device-width, initial-scale=
1.0")
14:55:38 web.1  |     6| 
14:55:38 web.1  |   > 7|     title= meta.title
14:55:38 web.1  |     8|     meta(name="description", content= meta.description)
14:55:38 web.1  |     9|     link(rel='image_src', type='image/png', href= meta.image)
14:55:38 web.1  |     10| 
14:55:38 web.1  | 
14:55:38 web.1  | Cannot read property 'title' of undefined
14:55:38 web.1  |     at eval (eval at <anonymous> (/app/node_modules/jade/lib/jade.js:160:8),
 <anonymous>:24:62)
14:55:38 web.1  |     at res (/app/node_modules/jade/lib/jade.js:161:38)
14:55:38 web.1  |     at Object.exports.render (/app/node_modules/jade/lib/jade.js:257:10)
14:55:38 web.1  |     at Object.exports.renderFile (/app/node_modules/jade/lib/jade.js:293:18)
14:55:38 web.1  |     at View.exports.renderFile [as engine] (/app/node_modules/jade/lib/jade.
js:278:21)
14:55:38 web.1  |     at View.render (/app/node_modules/express/lib/view.js:75:8)
14:55:38 web.1  |     at Function.app.render (/app/node_modules/express/lib/application.js:505
:10)
14:55:38 web.1  |     at ServerResponse.res.render (/app/node_modules/express/lib/response.js:
717:7)
14:55:38 web.1  |     at Object.handle (/app/server.js:82:10)
14:55:38 web.1  |     at IncomingMessage.next (/app/node_modules/express/node_modules/connect/
lib/proto.js:185:17)
15:01:07 web.1  | GET /api/v2/users/team 200 6ms
15:01:07 web.1  | { [Error: ENOENT, open 'metrics/metrics.json'] errno: 34, code: 'ENOENT', pa
th: 'metrics/metrics.json' }
15:01:07 web.1  | GET /counts 500 32ms
15:01:07 web.1  | GET /api/v2/dashboards 200 6ms
15:42:03 web.1  | GET / 200 29ms - 2.3kb
16:00:37 web.1  | GET / 200 27ms
16:00:37 web.1  | GET /api/v2/users/team 200 5ms
16:00:37 web.1  | { [Error: ENOENT, open 'metrics/metrics.json'] errno: 34, code: 'ENOENT', pa
th: 'metrics/metrics.json' }
16:00:37 web.1  | GET /counts 500 22ms
16:00:38 web.1  | GET /api/v2/dashboards 200 7ms
SIGTERM received
16:00:53 system | sending SIGTERM to all processes
16:00:53 web.1  | exited with code 143
16:00:53 web.1  | started with pid 11
16:00:54 web.1  | info: socket.io started
16:00:54 web.1  | Express server listening on port 5000
```

The cause for me trying to restart the container was it not displaying any actual numbers after running the migration script.
Now it doesn't even run anymore :(

Maybe you have seen similar behaviour before?

**Comment by pjnovas** [comment]
Oh, sorry, I closed it because your question was answered, I was waiting for a re-open if some thing come up, I'm re-opening now.

Check the script line:
https://github.com/danzajdband/hackdash/blob/master/utils/dashboardsCovers.js#L63

It has to output the updated dashboards, if you kill it before the print, it wont be finished.
If it is printing without any number, try adding a log for the error parameter to see what is happening.

For the landing counter you need to run the metrics process: https://github.com/danzajdband/hackdash/tree/master/metrics

I'm sorry about this, I'm gonna have to review the installation process to reflect the changes of this new release.

Here is a project structure overview it could help:
https://github.com/danzajdband/hackdash/wiki/Project-Overview

**Comment by pjnovas** [comment]
@almereyda feel free to re-open if there is a still an issue.
Also, I have created a wiki for the initial instalation [here](https://github.com/danzajdband/hackdash/wiki)
